# Generated by Django 3.1.7 on 2022-04-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('model_name', models.CharField(max_length=120, unique=True)),
                ('gender', models.CharField(choices=[('M', 'мужской'), ('W', 'женский')], default='M', max_length=12)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='language.language')),
            ],
        ),
    ]
