# Generated by Django 3.1.7 on 2022-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220428_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='username',
        ),
    ]
