# Generated by Django 3.1.7 on 2022-04-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['process_at']},
        ),
    ]
