# Generated by Django 3.1.7 on 2022-04-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20220428_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
