# Generated by Django 3.1.7 on 2022-04-27 10:52

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('short_title', models.CharField(max_length=5, unique=True)),
                ('flag', easy_thumbnails.fields.ThumbnailerImageField(default='images/language/flag.png', upload_to='images/language/flags/')),
            ],
        ),
    ]
